version: 2

sources:
  - name: staging
    schema: staging
    tables:
      - name: orders
      - name: customers
      - name: products
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: sellers
      - name: geolocation
      - name: category_translation